apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-demo

resources:
  - namespace.yaml

bases:
  - base/grafana

helmCharts:
  - name: ssl-exporter-chart
    namespace: monitoring-demo
    includeCRDs: false
    releaseName: ssl-exporter
    version: 0.1.1
    # valuesFile: values.yaml
    repo: https://znqerz.github.io/ssl-exporter-chart
