{{- if .Values.configMap.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "ssl-exporter-chart.fullname" . }}
  labels:
    {{- include "ssl-exporter-chart.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ .Values.configMap.data  | nindent 4}}
{{- end }}