apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssl-exporter-chart.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "ssl-exporter-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ssl-exporter-chart.selectorLabels" . | nindent 4 }}
  sessionAffinity: 
    {{ .Values.service.sessionAffinity | quote}}
